-- This file is intentionally empty.
--
-- Schema is managed exclusively via bin/bridge-migrate.sh (forward-only
-- migration runner with checksum tracking in schema_migrations).
--
-- On a fresh volume, mounting DDL here caused a collision: Postgres ran
-- this file before bridge-migrate.sh, so migration 001 would fail with
-- "ERROR: type app_id already exists" (no IF NOT EXISTS on CREATE TYPE).
--
-- To bootstrap a fresh database:
--   1. Start the postgres-prod container:
--        docker compose -f docker-compose-prod.yml \
--                       -f docker-compose-prod-platform.yml up -d postgres-prod
--   2. Wait for healthcheck (pg_isready -U bridge -d bridge).
--   3. Apply all migrations:
--        bash /root/werkingflow-bridge/bin/bridge-migrate.sh
--   4. (Optional) Seed test data:
--        BRIDGE_SERVICE_TOKEN=<token> bash /root/werkingflow-bridge/bin/bridge-setup-db.sh
