#!/usr/bin/env bash
# =============================================================================
# generate-bridge-upstreams.sh — the ONE source for the per-topology nginx
# upstreams include (ADR-0006 items B/C).
# =============================================================================
# The shared docker/nginx.conf (OpenResty + Lua, used by BOTH bridges) is
# topology-AGNOSTIC: it contains no worker names. The only pieces that legitimately
# differ between primary and production are the worker set and the backup host —
# and they live in exactly one generated include per bridge:
#
#   scripts/generate-bridge-upstreams.sh primary    -> docker/upstreams-primary.conf
#   scripts/generate-bridge-upstreams.sh production  -> docker/upstreams-prod.conf
#   scripts/generate-bridge-upstreams.sh all         (writes both, the default)
#
# nginx.conf does `include /tmp/upstreams.conf;` (the compose envsubst's the
# mounted include first, to resolve ${BRIDGE_BACKUP_HOST}). Because there is only
# ONE nginx.conf and the worker set is emitted from ONE script, a route can never
# again exist on one bridge and not the other (the werking-energy Phase-4 drift).
#
# The worker sets below are the VERIFIED host ground truth (ADR-0006 cutover
# table, re-verified live 2026-07-01):
#   primary    : worker1..4                 (metrics-reader BRIDGE_WORKERS default)
#   production : worker-sahori, worker-kurt  (metrics-reader BRIDGE_WORKERS env)
#
# Regenerate + commit when the worker set changes (rare). Do NOT hand-edit the
# generated files — the header marks them, and bridge-parity-check.sh compares the
# in-container copy against the repo copy to catch drift.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="${ROOT}/docker"

# --- Topology table (single source of the per-bridge worker set) -------------
# primary: default pool has NO cross-host backup (dev/prod isolation — a dev
#          request must fail-fast, never spill onto the customer bridge). The
#          production-priority pool (claude_production) DOES back up to Server-2.
# production: the default pool backs up to the dev bridge (Model-B resilience:
#          both prod workers exhausted/down -> dev bridge serves). claude_production
#          is the same pool (prod has no separate "production reserve" to route to).
PRIMARY_WORKERS=(worker1 worker2 worker3 worker4)
PROD_WORKERS=(worker-sahori worker-kurt)

emit_upstream() {
    # $1 = upstream name, $2 = keepalive, $3 = "backup"|"nobackup", then worker names
    local name="$1"; local keepalive="$2"; local backup="$3"; shift 3
    echo "upstream ${name} {"
    local w
    for w in "$@"; do
        echo "    server ${w}:8000 weight=1 max_fails=0;"
    done
    if [ "$backup" = "backup" ]; then
        echo "    server \${BRIDGE_BACKUP_HOST}:8000 backup max_fails=1 fail_timeout=10s;"
    fi
    echo "    keepalive ${keepalive};"
    echo "}"
}

emit_target_dest_map() {
    # Vestigial map preserved from nginx.conf (defined but not used in proxy_pass;
    # kept for structural parity + the "unavailable" sentinel). First worker is
    # the default. $@ = worker names.
    local first="$1"
    echo "map \$target_worker \$target_dest {"
    echo "    default        \"${first}:8000\";"
    local w
    for w in "$@"; do
        echo "    \"${w}\"  \"${w}:8000\";"
    done
    echo "    \"unavailable\"  \"claude_unavail\";"
    echo "}"
}

generate() {
    local id="$1"
    local -a workers
    local default_backup
    case "$id" in
        primary)
            workers=("${PRIMARY_WORKERS[@]}")
            default_backup="nobackup"   # isolation: default pool must not spill to prod
            ;;
        production)
            workers=("${PROD_WORKERS[@]}")
            default_backup="backup"     # Model-B: default pool backs up to dev bridge
            ;;
        *)
            echo "ERROR: unknown topology '$id' (primary|production)" >&2
            return 1
            ;;
    esac

    cat <<HEADER
# =============================================================================
# AUTO-GENERATED by scripts/generate-bridge-upstreams.sh ${id} — DO NOT EDIT
# =============================================================================
# The per-topology worker set for the SHARED docker/nginx.conf (ADR-0006 B/C).
# This is the ONLY nginx difference between the two bridges. \${BRIDGE_BACKUP_HOST}
# is resolved by the compose envsubst before nginx loads this file.
#   topology : ${id}
#   workers  : ${workers[*]}
# Regenerate with the generator; never hand-edit. bridge-parity-check.sh verifies
# the in-container copy matches this repo file.
# =============================================================================

HEADER

    echo "# Round-robin default pool (used by /health, Lua-routed /v1 SSE, default /)."
    emit_upstream claude_workers 32 "$default_backup" "${workers[@]}"
    echo

    echo "# Per-worker map — vestigial (\$target_dest is not used in a proxy_pass;"
    echo "# kept for structural parity + the \"unavailable\" sentinel)."
    emit_target_dest_map "${workers[@]}"
    echo

    echo "# Production-priority pool (X-Priority: production). Backs up to"
    echo "# \${BRIDGE_BACKUP_HOST}: Server-2 on primary, the dev bridge on production."
    emit_upstream claude_production 16 backup "${workers[@]}"
}

main() {
    local target="${1:-all}"
    case "$target" in
        primary)    generate primary    > "${OUT_DIR}/upstreams-primary.conf"; echo "[gen] wrote docker/upstreams-primary.conf" ;;
        production) generate production  > "${OUT_DIR}/upstreams-prod.conf";    echo "[gen] wrote docker/upstreams-prod.conf" ;;
        all)
            generate primary    > "${OUT_DIR}/upstreams-primary.conf"; echo "[gen] wrote docker/upstreams-primary.conf"
            generate production  > "${OUT_DIR}/upstreams-prod.conf";    echo "[gen] wrote docker/upstreams-prod.conf"
            ;;
        *) echo "Usage: generate-bridge-upstreams.sh [primary|production|all]" >&2; exit 1 ;;
    esac
}

main "$@"
