#!/bin/bash
# =============================================================================
# Smart Worker Routing — Nginx Upstream Manager
# =============================================================================
# Reads CC usage snapshots from Bridge metrics API and updates nginx upstream
# weights + up/down so traffic is steered AWAY from near-exhausted workers
# BEFORE they hit the hard wall. Runs every 10 minutes via cron.
#
# How it works:
#   1. Fetches latest account usage from /v1/metrics/cc-usage-history
#   2. For each worker:
#        weekly < THROTTLE_START          → weight=100  (full share)
#        weekly ∈ [THROTTLE_START, DOWN]  → weight ramps 100 → MIN_WEIGHT
#        weekly >= DOWN                   → `down`      (no traffic)
#      Session % is evaluated the same way; the stricter value wins.
#   3. Writes /etc/nginx/conf.d/upstream-workers.conf
#   4. Reloads nginx (zero-downtime)
#
# Rationale: the bridge's in-process AdaptiveLoadLimiter ALSO throttles on the
# same weekly %, returning structured throttle envelopes. Weighted LB routing
# means fewer calls reach the over-committed worker in the first place, so
# the throttle envelope is a last-resort fallback rather than the common case.
#
# Safety: If ALL workers >= DOWN, keeps all active (let nginx failover handle it)
#
# Install: crontab -e → */10 * * * * /root/werkingflow-bridge/scripts/smart-worker-routing.sh >> /var/log/smart-routing.log 2>&1
# =============================================================================

set -euo pipefail

BRIDGE_URL="http://localhost:8000"
NGINX_CONTAINER="eco-wrapper-lb"
UPSTREAM_FILE="/etc/nginx/conf.d/upstream-workers.conf"
THRESHOLD=95              # Worker marked `down` at/above this weekly or session %
THROTTLE_START=80         # Weight starts dropping at this %
MIN_WEIGHT=10             # Minimum non-down weight (10% of full 100 share)
LOG_TAG="[smart-routing]"

log() { echo "$(date '+%Y-%m-%d %H:%M:%S') $LOG_TAG $*"; }

# ---- Fetch & decide ----
UPSTREAM=$(curl -s --max-time 10 "$BRIDGE_URL/v1/metrics/cc-usage-history?hours=1&limit=1" 2>/dev/null | python3 -c "
import sys, json

THRESHOLD       = $THRESHOLD
THROTTLE_START  = $THROTTLE_START
MIN_WEIGHT      = $MIN_WEIGHT
ACCOUNT_MAP = {
    'engelmann': ('worker1', 'rafael@engelmann.at'),
    'office':    ('worker2', 'office@data-energyneering.at'),
    'gmail':     ('worker3', 'engelmann.rafaelo@gmail.com'),
    'werking':   ('worker4', 'werkingflow'),
}

def compute_weight(weekly, session):
    # Stricter value wins. Ramp 100 → MIN_WEIGHT linearly across [START, DOWN).
    pct = max(weekly, session)
    if pct < THROTTLE_START:
        return 100
    if pct >= THRESHOLD:
        return 0  # down
    span = max(1.0, THRESHOLD - THROTTLE_START)
    t = (pct - THROTTLE_START) / span  # 0..1
    w = round(100 - t * (100 - MIN_WEIGHT))
    return max(MIN_WEIGHT, int(w))

try:
    data = json.load(sys.stdin)
except:
    print('ERROR')
    sys.exit(1)

snapshots = data.get('snapshots', [])
if not snapshots:
    print('ERROR')
    sys.exit(1)

accounts = snapshots[0].get('accounts', [])
workers = {}

for acc in accounts:
    name = acc.get('account', '')
    if name not in ACCOUNT_MAP:
        continue
    worker, email = ACCOUNT_MAP[name]
    # ONLY these two limits decide — extra-usage etc. is ignored on purpose.
    weekly  = acc.get('weeklyAllModels', {}).get('percent', 0)
    session = acc.get('currentSession', {}).get('percent', 0)
    weight  = compute_weight(weekly, session)
    is_down = (weight == 0)
    workers[worker] = {
        'email': email, 'weekly': weekly, 'session': session,
        'weight': weight, 'down': is_down,
    }

# Safety: if all down, keep all up at min weight
if all(w['down'] for w in workers.values()):
    for w in workers.values():
        w['down'] = False
        w['weight'] = MIN_WEIGHT
    print('# FALLBACK: all workers >= {}% — keeping all active at min weight'.format(THRESHOLD), file=sys.stderr)

# Generate upstream block
ts = snapshots[0].get('ts', 0)
from datetime import datetime
ts_str = datetime.fromtimestamp(ts).strftime('%H:%M') if ts else '?'

print('# Auto-generated by smart-worker-routing.sh')
print('# Last snapshot: {} | Down-threshold: {}% | Ramp-start: {}% | Min-weight: {}'
      .format(ts_str, THRESHOLD, THROTTLE_START, MIN_WEIGHT))
print('upstream claude_workers {')
for worker in ['worker1', 'worker2', 'worker3', 'worker4']:
    if worker not in workers:
        print('    server {}:8000 weight=100 max_fails=5 fail_timeout=300s;'.format(worker))
        continue
    w = workers[worker]
    if w['down']:
        print('    server {}:8000 down;  # {} weekly={}% session={}% rate-limited'
              .format(worker, w['email'], w['weekly'], w['session']))
    else:
        print('    server {}:8000 weight={} max_fails=3 fail_timeout=300s;  # {} weekly={}% session={}%'
              .format(worker, w['weight'], w['email'], w['weekly'], w['session']))
print('')
print('    keepalive 32;')
print('}')
" 2>&1)

if echo "$UPSTREAM" | head -1 | grep -q "^ERROR"; then
    log "ERROR: Failed to fetch/parse usage snapshot. Skipping."
    exit 1
fi

# Log worker status
log "$(echo "$UPSTREAM" | grep -c 'down;') worker(s) marked down"
echo "$UPSTREAM" | grep 'server ' | while read -r line; do
    log "  $line"
done

# ---- Write upstream config into nginx container ----
# Write to temp file, copy into container
TMPFILE=$(mktemp)
echo "$UPSTREAM" > "$TMPFILE"

# Check if config actually changed
CURRENT=$(docker exec "$NGINX_CONTAINER" cat "$UPSTREAM_FILE" 2>/dev/null || echo "")
NEW=$(cat "$TMPFILE")

# Compare ignoring the timestamp comment line
CURRENT_CLEAN=$(echo "$CURRENT" | grep -v "^# Last snapshot:" | grep -v "^# Auto-generated")
NEW_CLEAN=$(echo "$NEW" | grep -v "^# Last snapshot:" | grep -v "^# Auto-generated")

if [ "$CURRENT_CLEAN" = "$NEW_CLEAN" ]; then
    log "No changes needed."
    rm -f "$TMPFILE"
    exit 0
fi

docker cp "$TMPFILE" "${NGINX_CONTAINER}:${UPSTREAM_FILE}"
rm -f "$TMPFILE"

# ---- Validate & reload ----
if docker exec "$NGINX_CONTAINER" nginx -t 2>&1 | grep -q "successful"; then
    docker exec "$NGINX_CONTAINER" nginx -s reload
    log "Nginx reloaded successfully."
else
    log "ERROR: Nginx config test failed! Removing bad config."
    docker exec "$NGINX_CONTAINER" rm -f "$UPSTREAM_FILE"
    docker exec "$NGINX_CONTAINER" nginx -s reload
    exit 1
fi
